# put your secret values and credentials here. do not share this file and do not push it to github
api_secret_key = "9dfec943-f05c-4fdc-a309-074698500eb1" # please set me up!

[destination.mssql.credentials]
database = "dlt_database_name" # please set me up!
password = "Dummy@123" # please set me up!
username = "dlt-server-admin" # please set me up!
host = "dlt-server-name.database.windows.net" # please set me up!
port = 1433
connect_timeout = 15
odbc_driver = "ODBC Driver 18 for SQL Server" # please set me up!
