# put your secret values and credentials here. do not share this file and do not push it to github
[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.bigquery]
location = "US"
[destination.bigquery.credentials]
project_id = "hive-project-******" # please set me up!
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASC*********IBAQCu1UFjMOeeMJkV==\n-----END PRIVATE KEY-----\n" # please set me up!
client_email = "****pipeline-service-account@hive-project-******.iam.gserviceaccount.com" # please set me up!

