# put your secret values and credentials here. do not share this file and do not push it to github
api_secret_key = "2aa313de4ceea3ecd446a6c2de1218744462d606" # this is fake data. please set your actual value

[destination.bigquery]
location = "US"
[destination.bigquery.credentials]
project_id = "hive-project-403905"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCu1UFjMOeeMJkV==\n-----END PRIVATE KEY-----\n" # this is fake data, please set your actual value
client_email = "dlt-service-account@hive-project-403905.iam.gserviceaccount.com" # this is fake data, please set your actual value
