# put your secret values and credentials here. do not share this file and do not push it to github
api_secret_key = "*******-f05c-4fdc-a309-*********" # please set me up!

[destination.mssql.credentials]
database = "****database_name" # please set me up!
password = "D********" # please set me up!
username = "****server-admin" # please set me up!
host = "**********.database.windows.net" # please set me up!
port = 1433
connect_timeout = 15
odbc_driver = "ODBC Driver 18 for SQL Server" # please set me up!
